# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  logs:
    dropbox: debug
    homeassistant.components.backup: debug
    homeassistant.helpers.config_entry_oauth2_flow: debug # OAuth2 helper internals :contentReference[oaicite:0]{index=0}
    homeassistant.components.application_credentials: debug # Application Credentials flow :contentReference[oaicite:1]{index=1}
    custom_components.dropboxbackup: debug
